CREATE TABLE permissions (
  id UUID PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  scope VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  status VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
